In [2]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
arr = np.random.randint(0,50,10)

In [4]:
arr


array([37, 43, 33, 47, 34, 47, 33,  3, 40,  0])

In [7]:
arr.reshape(2,5)

array([[37, 43, 33, 47, 34],
       [47, 33,  3, 40,  0]])

In [3]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.random.rand(5)

array([0.52970916, 0.27602212, 0.15757196, 0.169073  , 0.28402614])

In [6]:
np.random.rand(5,5)

array([[0.71766082, 0.46799297, 0.24399267, 0.31366105, 0.09913007],
       [0.92789667, 0.03294669, 0.25052247, 0.38163548, 0.07237557],
       [0.52163111, 0.06892079, 0.72083089, 0.95298765, 0.38236082],
       [0.39173634, 0.29116558, 0.49954536, 0.68536719, 0.81605043],
       [0.93297138, 0.79677433, 0.87225204, 0.80788846, 0.9101494 ]])

In [7]:
np.random.randn(2)

array([ 3.28229649, -0.58035984])

In [15]:
np.random.randint(1,100,2)

array([ 6, 16])

In [17]:
arr =  np.arange(25)

In [18]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])