In [5]:
import numpy as np

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
arr = np.random.randint(0,50,10)

In [4]:
arr


array([37, 43, 33, 47, 34, 47, 33,  3, 40,  0])

In [7]:
arr.reshape(2,5)

array([[37, 43, 33, 47, 34],
       [47, 33,  3, 40,  0]])